package structuresEecASN1

import "local/structures/defStructs"

// TTnss9
var TTnss9 = map[int]defStructs.TabRechercheTypeDc{
	0: {"Tnss9", 0xff000000, 0xa0000000, 0, &Tnss9},
	1: {"Tnss9", 0xff000000, 0xa1000000, 0, &Tnss9},
}

// Tnss9
var Tnss9 = map[int]defStructs.Champ{
	0: {"UMTSGSMPLMNCallDR", -1, 0, &CallDataRecord},
	1: {"Composite", -1, 0, &CompositeExt},
}

var CallDataRecord = map[int]defStructs.Champ{
	0:  {"transit", -1, 0, &Transit},
	1:  {"mSOriginating", -1, 0, &MSOriginating},
	2:  {"roamingCallForwarding", -1, 0, &RoamingCallForwarding},
	3:  {"callForwarding", -1, 0, &CallForwarding},
	4:  {"mSTerminating", -1, 0, &MSTerminating},
	5:  {"mSOriginatingSMS", -1, 0, &MSOriginatingSMSinMSC},
	7:  {"mSTerminatingSMS", -1, 0, &MSTerminatingSMSinMSC},
	9:  {"sSProcedure", -1, 0, &SSProcedure},
	14: {"iNincomingCall", -1, 0, &INIncomingCall},
	15: {"iNOutgoingCall", -1, 0, &INOutgoingCall},
	16: {"eventModule", -1, 0, &EventModule},
	17: {"iSDNOriginating", -1, 0, &ISDNOriginating},
	18: {"iSDNCallForwarding", -1, 0, &ISDNCallForwarding},
}

var CompositeExt = map[int]defStructs.Champ{
	0: {"UMTSGSMPLMNCallDR", -1, 0, &CallDataRecordComposite},
}

var CallDataRecordComposite = map[int]defStructs.Champ{
	0:  {"transit", -1, 0, &Transit},
	1:  {"mSOriginatingC", -1, 0, &MSOriginating},
	2:  {"roamingCallForwardingC", -1, 0, &RoamingCallForwarding},
	3:  {"callForwardingC", -1, 0, &CallForwarding},
	4:  {"mSTerminatingC", -1, 0, &MSTerminating},
	5:  {"mSOriginatingSMSC", -1, 0, &MSOriginatingSMSinMSC},
	7:  {"mSTerminatingSMSC", -1, 0, &MSTerminatingSMSinMSC},
	9:  {"sSProcedureC", -1, 0, &SSProcedure},
	14: {"iNincomingCall", -1, 0, &INIncomingCall},
	15: {"iNOutgoingCall", -1, 0, &INOutgoingCall},
	16: {"eventModule", -1, 0, &EventModule},
	17: {"iSDNOriginatingC", -1, 0, &ISDNOriginating},
	18: {"iSDNCallForwardingC", -1, 0, &ISDNCallForwarding},
}

var EventModule = map[int]defStructs.Champ{
	11: {"sSInvocationEventModule", -1, 0, &SSIEventModule},
	12: {"serviceSwitchEventModul", -1, 0, &ServiceSwitchEventModul},
	16: {"iNServiceDataEventModule", -1, 0, &INServiceDataEventModule},
	23: {"iSDNSSInvocationEventModule", -1, 0, &ISDNSSInvocationEventModule},
	25: {"handOverEventModule", -1, 0, &HandOverEventModule},
}

var MSTerminatingSMSinMSC = map[int]defStructs.Champ{
	3:  {"calledPartyNumber_MTS", -1, 5, nil},
	4:  {"calledSubscriberIMSI_MTS", -1, 5, nil},
	5:  {"calledSubscriberIMEI_MTS", -1, 5, nil},
	6:  {"dateForStartofCharge_MTS", -1, 14, nil},
	7:  {"timeForStartofCharge_MTS", -1, 15, nil},
	10: {"exchangeIdentity_MTS", -1, 1, nil},
	13: {"firstCalledLocInfo_MTS", -1, 5, nil},
	15: {"serviceCentreAddress_MTS", -1, 5, nil},
	28: {"numberOfShortMessages_MTS", -1, 0, nil},
	29: {"lastCalledLocInfo_MTS", -1, 0, nil},
	32: {"switchIdentity_MTS", -1, 0, nil},
	33: {"originatingAddress_MTS", -1, 5, nil},
	35: {"rNCidOfFirstRNC_MTS", -1, 0, nil},
	43: {"CalledSubscriberIMEISV", -1, 5, nil},
	52: {"firstCalledLocInfoExt_MTS", -1, 5, nil},
}

var Transit = map[int]defStructs.Champ{
	4:   {"callingPartyNumber_TR", -1, 5, nil},
	5:   {"calledPartyNumber_TR", -1, 5, nil},
	7:   {"disconnectingParty_TR", -1, 0, nil},
	8:   {"dateForStartofCharge_TR", -1, 14, nil},
	9:   {"timeForStartofCharge_TR", -1, 15, nil},
	11:  {"chargeableDuration_TR", -1, 15, nil},
	18:  {"numberOfMeterPulses_TR", -1, 0, nil},
	19:  {"exchangeIdentity_TR", -1, 1, nil},
	21:  {"outgoingRoute_TR", -1, 0, nil},
	22:  {"incomingRoute_TR", -1, 1, nil},
	25:  {"iNMarkingOfMS_TR", -1, 0, nil},
	29:  {"originalCalledNumber_TR", -1, 0, nil},
	30:  {"redirectingNumber_TR", -1, 0, nil},
	38:  {"lastPartialOutput_TR", -1, 0, nil},
	39:  {"partialOutputRecNum_TR", -1, 0, nil},
	45:  {"switchIdentity_TR", -1, 0, nil},
	50:  {"translatedNum_TR", -1, 5, nil},
	51:  {"bCSMTDPData1_TR", -1, 0, &bCSMTDPData_TRComp},
	52:  {"bCSMTDPData2_TR", -1, 0, &bCSMTDPData_TRComp},
	53:  {"bCSMTDPData3_TR", -1, 0, &bCSMTDPData_TRComp},
	54:  {"bCSMTDPData4_TR", -1, 0, &bCSMTDPData_TRComp},
	55:  {"bCSMTDPData5_TR", -1, 0, &bCSMTDPData_TRComp},
	56:  {"bCSMTDPData6_TR", -1, 0, &bCSMTDPData_TRComp},
	57:  {"bCSMTDPData7_TR", -1, 0, &bCSMTDPData_TRComp},
	58:  {"bCSMTDPData8_TR", -1, 0, &bCSMTDPData_TRComp},
	59:  {"bCSMTDPData9_TR", -1, 0, &bCSMTDPData_TRComp},
	60:  {"bCSMTDPData10_TR", -1, 0, &bCSMTDPData_TRComp},
	61:  {"gSMCallReferenceNumber_TR", -1, 0, nil},
	62:  {"c7ChargingMessage_TR", -1, 0, nil},
	63:  {"c7FirstCHTMessage_TR", -1, 0, nil},
	64:  {"c7SecondCHTMessage_TR", -1, 0, nil},
	67:  {"mSCAddress_TR", -1, 16, nil},
	93:  {"multimediaInformation_TR", -1, 0, nil},
	124: {"internationalIncomingCall_TR", -1, 0, nil},
	125: {"originatingLocationNumber_TR", -1, 5, nil},
}

var bCSMTDPData_TRComp = map[int]defStructs.Champ{
	0: {"ServiceKey", -1, 0, nil},
	1: {"gsmSCFAddress", -1, 0, nil},
}

var MSOriginating = map[int]defStructs.Champ{
	4:   {"callingPartyNumber_MSO", -1, 5, nil},
	5:   {"callingSubscriberIMSI_MSO", -1, 5, nil},
	6:   {"callingSubscriberIMEI_MSO", -1, 5, nil},
	7:   {"calledPartyNumber_MSO", -1, 5, nil},
	8:   {"disconnectingParty_MSO", -1, 0, nil},
	9:   {"dateForStartofCharge_MSO", -1, 14, nil},
	10:  {"timeForStartofCharge_MSO", -1, 15, nil},
	12:  {"chargeableDuration_MSO", -1, 0, nil},
	15:  {"callingSubscriberIMEISV_MSO", -1, 5, nil},
	20:  {"exchangeIdentity_MSO", -1, 1, nil},
	22:  {"outgoingRoute_MSO", -1, 0, nil},
	25:  {"originatingLocationNumber_MSO", -1, 0, nil},
	26:  {"timeForTCSeizureCalling_MSO", -1, 15, nil},
	27:  {"firstCallingLocInfo_MSO", -1, 0, nil},
	29:  {"teleServiceCode_MSO", -1, 0, nil},
	30:  {"bearerServiceCode_MSO", -1, 0, nil},
	31:  {"transparencyIndicator_MSO", -1, 0, nil},
	32:  {"firstRadioChannelUsed_MSO", -1, 0, nil},
	38:  {"numberOfMeterPulses_MSO", -1, 0, nil},
	39:  {"c7ChargingMessage_MSO", -1, 0, nil},
	40:  {"c7FirstCHTMessage_MSO", -1, 0, nil},
	41:  {"c7SecondCHTMessage_MSO", -1, 0, nil},
	47:  {"iNMarkingOfMS_MSO", -1, 0, nil},
	48:  {"lastPartialOutput", -1, 0, nil},
	49:  {"partialOutputRecNum", -1, 0, nil},
	50:  {"cUGInterlockCode", -1, 0, nil},
	51:  {"cUGIndex", -1, 0, nil},
	52:  {"cUGOutgoingAccessUsed", -1, 0, nil},
	53:  {"cUGOutgoingAccessIndicator", -1, 0, nil},
	67:  {"switchIdentity_MSO", -1, 0, nil},
	69:  {"frequencyBandSupported_MSO", -1, 0, nil},
	74:  {"translatedNumber_MSO", -1, 0, nil},
	75:  {"bCSMTDPData1_MSO", -1, 0, &BCSMTDPData_MSO},
	76:  {"bCSMTDPData2_MSO", -1, 0, &BCSMTDPData_MSO},
	77:  {"bCSMTDPData3_MSO", -1, 0, &BCSMTDPData_MSO},
	78:  {"bCSMTDPData4_MSO", -1, 0, &BCSMTDPData_MSO},
	79:  {"bCSMTDPData5_MSO", -1, 0, &BCSMTDPData_MSO},
	80:  {"bCSMTDPData6_MSO", -1, 0, &BCSMTDPData_MSO},
	81:  {"bCSMTDPData7_MSO", -1, 0, &BCSMTDPData_MSO},
	82:  {"bCSMTDPData8_MSO", -1, 0, &BCSMTDPData_MSO},
	83:  {"bCSMTDPData9_MSO", -1, 0, &BCSMTDPData_MSO},
	84:  {"bCSMTDPData10_MSO", -1, 0, &BCSMTDPData_MSO},
	85:  {"gSMCallReferenceNumber_MSO", -1, 0, nil},
	86:  {"mSCAddress_MSO", -1, 0, nil},
	91:  {"incomingAssignedRoute", -1, 1, nil},
	93:  {"rANAPCauseCode", -1, 0, nil},
	94:  {"gsmSCFAddress", -1, 0, nil},
	98:  {"bSSMAPCauseCode", -1, 0, nil},
	101: {"trafficClass_MSO", -1, 0, nil},
	103: {"rNCidOfFirstRNC_MSO", -1, 0, nil},
	120: {"oICK_MSO", -1, 0, nil},
	143: {"callingSubscriberIMEISV_MSO", -1, 0, nil},
	153: {"iuCodec", -1, 0, nil},
	163: {"emergencyServiceCategory", -1, 0, nil},
}

var BCSMTDPData_MSO = map[int]defStructs.Champ{
	0: {"ServiceKey", -1, 0, nil},
	1: {"gsmSCFAddress", -1, 0, nil},
}

var RoamingCallForwarding = map[int]defStructs.Champ{
	4:   {"callingPartyNumber_RCF", -1, 5, nil},
	5:   {"calledPartyNumber_RCF", -1, 5, nil},
	6:   {"calledSubscriberIMSI_RCF", -1, 5, nil},
	7:   {"mobileStationRNb_RCF", -1, 0, nil},
	8:   {"disconnectingParty_RCF", -1, 0, nil},
	9:   {"dateForStartofCharge_RCF", -1, 14, nil},
	10:  {"timeForStartofCharge_RCF", -1, 15, nil},
	12:  {"chargeableDuration_RCF", -1, 15, nil},
	19:  {"exchangeIdentity_RCF", -1, 1, nil},
	21:  {"outgoingRoute_RCF", -1, 1, nil},
	22:  {"incomingRoute_RCF", -1, 1, nil},
	28:  {"originalCalledNumber_RCF", -1, 0, nil},
	29:  {"redirectingNumber_RCF", -1, 0, nil},
	34:  {"c7ChargingMessage_RCF", -1, 0, nil},
	35:  {"c7FirstCHTMessage_RCF", -1, 0, nil},
	36:  {"c7SecondCHTMessage_RCF", -1, 0, nil},
	39:  {"lastPartialOutput_RCF", -1, 0, nil},
	40:  {"partialOutputRecNum_RCF", -1, 0, nil},
	42:  {"cUGInterlockCode_RCF", -1, 0, nil},
	43:  {"cUGOutgoingAccessIndicator_RCF", -1, 0, nil},
	47:  {"multimediaInformation_RCF", -1, 0, nil},
	48:  {"switchIdentity_RCF", -1, 0, nil},
	53:  {"gSMCallReferenceNumber_RCF", -1, 0, nil},
	54:  {"mSCAddress_RCF", -1, 16, nil},
	80:  {"mTRFIndicator_RCF", -1, 0, nil},
	124: {"internationalIncomingCall_RCF", -1, 0, nil},
	125: {"originatingLocationNumber_RCF", -1, 0, nil},
}

var CallForwarding = map[int]defStructs.Champ{
	4:   {"callingPartyNumber_CF", -1, 5, nil},
	5:   {"calledPartyNumber_CF", -1, 5, nil},
	6:   {"originalCalledNumber_CF", -1, 5, nil},
	7:   {"redirectingNumber_CF", -1, 0, nil},
	10:  {"redirectingIMSI_CF", -1, 0, nil},
	11:  {"mobileStationRNb_CF", -1, 0, nil},
	12:  {"disconnectingParty_CF", -1, 0, nil},
	13:  {"dateForStartofCharge_CF", -1, 14, nil},
	14:  {"timeForStartofCharge_CF", -1, 15, nil},
	16:  {"chargeableDuration_CF", -1, 15, nil},
	23:  {"exchangeIdentity_CF", -1, 0, nil},
	25:  {"outgoingRoute_CF", -1, 2, nil},
	26:  {"incomingRoute_CF", -1, 2, nil},
	28:  {"originatingLocationNumber_CF", -1, 0, nil},
	34:  {"numberOfMeterPulses_CF", -1, 0, nil},
	35:  {"c7ChargingMessage_CF", -1, 0, nil},
	36:  {"c7FirstCHTMessage_CF", -1, 0, nil},
	37:  {"c7SecondCHTMessage_CF", -1, 0, nil},
	40:  {"iNMarkingOfMS_CF", -1, 0, nil},
	41:  {"lastPartialOutput_CF", -1, 0, nil},
	42:  {"partialOutputRecNum_CF", -1, 0, nil},
	44:  {"cUGInterlockCode_CF", -1, 0, nil},
	45:  {"cUGIndex_CF", -1, 0, nil},
	46:  {"cUGOutgoingAccessUsed", -1, 0, nil},
	47:  {"cUGOutgoingAccessIndicator", -1, 0, nil},
	50:  {"presentationIndicator_CF", -1, 0, nil},
	56:  {"switchIdentity_CF", -1, 0, nil},
	61:  {"translatedNumber_CF", -1, 0, nil},
	62:  {"cAMELInitiatedCallForwarding_CF", -1, 0, nil},
	63:  {"bCSMTDPData1_CF", -1, 0, &bCSMTDPData_CF},
	64:  {"bCSMTDPData2_CF", -1, 0, &bCSMTDPData_CF},
	65:  {"bCSMTDPData3_CF", -1, 0, &bCSMTDPData_CF},
	66:  {"bCSMTDPData4_CF", -1, 0, &bCSMTDPData_CF},
	67:  {"bCSMTDPData5_CF", -1, 0, &bCSMTDPData_CF},
	68:  {"bCSMTDPData6_CF", -1, 0, &bCSMTDPData_CF},
	69:  {"bCSMTDPData7_CF", -1, 0, &bCSMTDPData_CF},
	70:  {"bCSMTDPData8_CF", -1, 0, &bCSMTDPData_CF},
	71:  {"bCSMTDPData9_CF", -1, 0, &bCSMTDPData_CF},
	72:  {"bCSMTDPData10_CF", -1, 0, &bCSMTDPData_CF},
	73:  {"gSMCallReferenceNumber_CF", -1, 0, nil},
	74:  {"mSCAddress_CF", -1, 0, nil},
	103: {"multimediaInformation_CF", -1, 0, nil},
	120: {"oICK_CF", -1, 0, nil},
	124: {"internationalIncomingCall_CF", -1, 0, nil},
}

var bCSMTDPData_CF = map[int]defStructs.Champ{
	0: {"ServiceKey", -1, 0, nil},
	1: {"gsmSCFAddress", -1, 0, nil},
}

var MSTerminating = map[int]defStructs.Champ{
	4:   {"callingPartyNumber_MST", -1, 5, nil},
	5:   {"calledPartyNumber_MST", -1, 5, nil},
	6:   {"calledSubscriberIMSI_MST", -1, 5, nil},
	7:   {"calledSubscriberIMEI_MST", -1, 5, nil},
	9:   {"disconnectingParty_MST", -1, 0, nil},
	10:  {"dateForStartofCharge_MST", -1, 14, nil},
	11:  {"timeForStartofCharge_MST", -1, 15, nil},
	13:  {"chargeableDuration_MST", -1, 15, nil},
	20:  {"exchangeIdentity_MST", -1, 0, nil},
	23:  {"incomingRoute_MST", -1, 0, nil},
	26:  {"timeForTCSeizureCalled_MST", -1, 0, nil},
	27:  {"firstCalledLocInfo_MST", -1, 0, nil},
	29:  {"teleServiceCode_MST", -1, 0, nil},
	30:  {"bearerServiceCode_MST", -1, 0, nil},
	31:  {"transparencyIndicator_MST", -1, 0, nil},
	32:  {"firstRadioChannelUsed_MST", -1, 0, nil},
	36:  {"originalCalledNumber_MST", -1, 0, nil},
	37:  {"redirectingNumber_MST", -1, 0, nil},
	51:  {"cUGInterlockCode_MST", -1, 0, nil},
	52:  {"cUGIndex_MST", -1, 0, nil},
	53:  {"cUGIncomingAccessUsed_MST", -1, 0, nil},
	57:  {"presentationIndicator_MST", -1, 0, nil},
	65:  {"mSCAddress_MST", -1, 0, nil},
	66:  {"switchIdentity_MST", -1, 0, nil},
	68:  {"frequencyBandSupported_MST", -1, 0, nil},
	73:  {"gSMCallReferenceNumber_MST", -1, 0, nil},
	78:  {"outgoingAssignedRoute_MST", -1, 0, nil},
	81:  {"gsmSCFAddress_MST", -1, 0, nil},
	85:  {"bSSMAPCauseCode_MST", -1, 0, nil},
	87:  {"trafficClass_MST", -1, 0, nil},
	88:  {"rANAPCauseCode_MST", -1, 0, nil},
	89:  {"rNCidOfFirstRNC_MST", -1, 0, nil},
	116: {"calledSubscriberIMEISV_MST", -1, 0, nil},
	124: {"internationalIncomingCall_MST", -1, 0, nil},
	125: {"originatingLocationNumber_MST", -1, 0, nil},
}

var MSOriginatingSMSinMSC = map[int]defStructs.Champ{
	4:  {"callingPartyNumber_MOS", -1, 5, nil},
	5:  {"callingSubscriberIMSI_MOS", -1, 5, nil},
	6:  {"callingSubscriberIMEI_MOS", -1, 5, nil},
	7:  {"dateForStartofCharge_MOS", -1, 14, nil},
	8:  {"timeForStartofCharge_MOS", -1, 15, nil},
	11: {"exchangeIdentity_MOS", -1, 0, nil},
	14: {"firstCallingLocationInformation_MOS", -1, 0, nil},
	16: {"serviceCentreAddress_MOS", -1, 0, nil},
	17: {"callingSubscriberIMEISV_MOS", -1, 0, nil},
	31: {"switchIdentity_MOS", -1, 0, nil},
	32: {"destinationAddress_MOS", -1, 0, nil},
	35: {"rNCidOfFirstRNC_MOS", -1, 0, nil},
	55: {"firstCallingLocationInformationExtension_MOS", -1, 0, nil},
}

var SSProcedure = map[int]defStructs.Champ{
	4:  {"callingPartyNumber_SS", -1, 5, nil},
	5:  {"callingSubscriberIMSI_SS", -1, 5, nil},
	6:  {"callingSubscriberIMEI_SS", -1, 5, nil},
	7:  {"dateForStartofCharge_SS", -1, 14, nil},
	8:  {"timeForStartofCharge_SS", -1, 15, nil},
	10: {"exchangeIdentity_SS", -1, 0, nil},
	12: {"firstCallingLocationInformation_SS", -1, 8, nil},
	13: {"callingSubscriberIMEISV_SS", -1, 0, nil},
	23: {"uSSDApplicationIdentifier_SS", -1, 0, nil},
	24: {"uSSDServiceCode_SS", -1, 0, nil},
	25: {"uSSDProcedureCode_SS", -1, 0, nil},
	26: {"networkInitiatedUSSDOperations_SS", -1, 0, nil},
	27: {"uSSDOperationIdentifier_SS", -1, 0, nil},
	32: {"switchIdentity_SS", -1, 0, nil},
	36: {"rNCidOfFirstRNC_SS", -1, 0, nil},
}

var INIncomingCall = map[int]defStructs.Champ{
	1:  {"switchIdentity", -1, 0, nil},
	3:  {"iNServiceTrigger", -1, 0, nil},
	5:  {"triggerData0", -1, 0, &TriggerData},
	6:  {"triggerData1", -1, 0, &TriggerData},
	7:  {"triggerData2", -1, 0, &TriggerData},
	8:  {"triggerData3", -1, 0, &TriggerData},
	9:  {"triggerData4", -1, 0, &TriggerData},
	10: {"triggerData5", -1, 0, &TriggerData},
	11: {"triggerData6", -1, 0, &TriggerData},
	12: {"triggerData7", -1, 0, &TriggerData},
	24: {"gSMCallReferenceNumber", -1, 0, nil},
	25: {"mSCAddress", -1, 0, nil},
}

var INOutgoingCall = map[int]defStructs.Champ{
	1:  {"switchIdentity", -1, 0, nil},
	3:  {"iNServiceTrigger", -1, 0, nil},
	5:  {"triggerData0", -1, 0, &TriggerData},
	6:  {"triggerData1", -1, 0, &TriggerData},
	7:  {"triggerData2", -1, 0, &TriggerData},
	8:  {"triggerData3", -1, 0, &TriggerData},
	9:  {"triggerData4", -1, 0, &TriggerData},
	10: {"triggerData5", -1, 0, &TriggerData},
	11: {"triggerData6", -1, 0, &TriggerData},
	12: {"triggerData7", -1, 0, &TriggerData},
	24: {"gSMCallReferenceNumber", -1, 0, nil},
	25: {"mSCAddress", -1, 0, nil},
}

var TriggerData = map[int]defStructs.Champ{
	0: {"triggerDetectionPoint", -1, 0, nil},
	1: {"ServiceKey", -1, 0, nil},
	3: {"pointCodeAndSubSystemnumber", -1, 0, nil},
	4: {"globalTitle", -1, 0, nil},
	5: {"globalTitleAndSubSystemNumber", -1, 0, nil},
}

var ISDNOriginating = map[int]defStructs.Champ{
	0:  {"trafficActivityCode_IS", -1, 0, nil},
	4:  {"chargedCallingPartyNumber_IS", -1, 0, nil},
	5:  {"calledPartyNumber_IS", -1, 5, nil},
	6:  {"disconnectingParty_IS", -1, 0, nil},
	7:  {"dateForStartofCharge_IS", -1, 14, nil},
	8:  {"timeForStartofCharge_IS", -1, 15, nil},
	10: {"chargeableDuration_IS", -1, 15, nil},
	14: {"exchangeIdentity_IS", -1, 0, nil},
	15: {"outgoingRoute_IS", -1, 0, nil},
	19: {"lastPartialOutput_IS", -1, 0, nil},
	20: {"partialOutputRecNum_IS", -1, 0, nil},
	23: {"presentationAndScreeningIndicator_IS", -1, 0, nil},
	28: {"causeCode_IS", -1, 0, nil},
	29: {"locationCode_IS", -1, 0, nil},
	30: {"networkProvidedCallingPartyNumber_IS", -1, 0, nil},
	32: {"callingPartyNumberSpecialArrangementInd_IS", -1, 0, nil},
	33: {"userProvidedCallingPartyNumber_IS", -1, 0, nil},
	50: {"switchIdentity_IS", -1, 0, nil},
}

var ISDNCallForwarding = map[int]defStructs.Champ{
	0:  {"trafficActivityCode", -1, 0, nil},
	4:  {"chargedCallingPartyNumber", -1, 0, nil},
	5:  {"calledPartyNumber", -1, 16, nil},
	6:  {"disconnectingParty", -1, 0, nil},
	7:  {"dateForStartofCharge", -1, 14, nil},
	8:  {"timeForStartofCharge", -1, 15, nil},
	10: {"chargeableDuration", -1, 0, nil},
	14: {"exchangeIdentity", -1, 0, nil},
	15: {"outgoingRoute", -1, 0, nil},
	17: {"originalCalledNumber", -1, 0, nil},
	18: {"redirectingNumber", -1, 16, nil},
	21: {"lastPartialOutput", -1, 0, nil},
	22: {"partialOutputRecNum", -1, 0, nil},
	25: {"presentationAndScreeningIndicator", -1, 0, nil},
	30: {"causeCode", -1, 0, nil},
	31: {"locationCode", -1, 0, nil},
	32: {"networkProvidedCallingPartyNumber", -1, 0, nil},
	33: {"callingPartyNumber", -1, 0, nil},
	51: {"switchIdentity", -1, 0, nil},
}

var SSIEventModule = map[int]defStructs.Champ{
	1:  {"sSCode", -1, 0, nil},
	3:  {"timeForEvent", -1, 0, nil},
	10: {"sSInvocationNotification", -1, 0, nil},
}

var ServiceSwitchEventModul = map[int]defStructs.Champ{
	1: {"timeForEvent", -1, 0, nil},
	2: {"serviceSwitchingType", -1, 0, nil},
}

var INServiceDataEventModule = map[int]defStructs.Champ{
	0: {"chargePartyDistributed", -1, 0, nil},
	1: {"chargePartySingle", -1, 0, nil},
	2: {"chargingUnitsAddition", -1, 0, nil},
	3: {"genericChargingDigits", -1, 0, nil},
	4: {"genericChargingNumbers", -1, 0, nil},
	5: {"serviceFeatureCode", -1, 0, nil},
	6: {"timeForEvent", -1, 0, nil},
	8: {"freeFormatData", -1, 0, nil},
	9: {"sSFLegID", -1, 0, nil},
}

var ISDNSSInvocationEventModule = map[int]defStructs.Champ{
	0: {"trafficActivityCode", -1, 0, nil},
	1: {"incompleteCallDataIndicator", -1, 0, nil},
}

var HandOverEventModule = map[int]defStructs.Champ{
	0: {"tAC", -1, 0, nil},
	1: {"timeForEvent", -1, 0, nil},
	2: {"rNCidOfTargetRNC", -1, 0, nil},
	3: {"incompleteCallDataIndicator", -1, 0, nil},
	4: {"targetLocationInformation", -1, 0, nil},
	5: {"radioChannelProperty", -1, 0, nil},
	6: {"channelCodingUsed", -1, 0, nil},
	7: {"bSSMAPCauseCode", -1, 0, nil},
	8: {"rANAPCauseCode", -1, 0, nil},
}
