package structuresEecCSV

import "local/structures/defStructs"

// TTv2oipAS
var TTv2oipAS = map[int]defStructs.TabRechercheTypeDc{
	0: {"Entete", 0xffffffff, 0x76657273, 0x2c, nil},
	1: {"Normal", 0x00000000, 0x00000000, 0x2c, &Tv2oipAS},
	//1: {"Failover", 0x00000000, 0x00000000, 0x2c, &failover},
}
var Tv2oipAS = map[int]defStructs.Champ{
	0:   {"recordId", -1, 0, nil},
	1:   {"serviceProviderId", -1, 0, nil},
	2:   {"type", -1, 0, nil},
	3:   {"userNumber", -1, 0, nil},
	4:   {"groupNumber", -1, 0, nil},
	5:   {"direction", -1, 0, nil},
	6:   {"callingNumber", -1, 0, nil},
	7:   {"callingPresentationIndicator", -1, 0, nil},
	8:   {"calledNumber", -1, 0, nil},
	9:   {"startTime", -1, 11, nil},
	10:  {"userTimeZone", -1, 0, nil},
	11:  {"answerIndicator", -1, 0, nil},
	12:  {"answerTime", -1, 11, nil},
	13:  {"releaseTime", -1, 11, nil},
	14:  {"terminationCause", -1, 0, nil},
	15:  {"networkType", -1, 0, nil},
	16:  {"Non utilise", -1, 0, nil},
	17:  {"dialedDigits", -1, 0, nil},
	18:  {"Call Category", -1, 0, nil},
	19:  {"networkCallType", -1, 0, nil},
	20:  {"networkTranslatedNumber", -1, 0, nil},
	21:  {"non utilise", -1, 0, nil},
	22:  {"releasingParty", -1, 0, nil},
	23:  {"route", -1, 0, nil},
	24:  {"networkCallID", -1, 0, nil},
	25:  {"codec", -1, 0, nil},
	26:  {"accessDeviceAddress", -1, 0, nil},
	27:  {"accessCallId", -1, 0, nil},
	28:  {"Non utilise dans contexte Orang", -1, 0, nil},
	29:  {"failoverCorrelationId", -1, 0, nil},
	30:  {"Non utilise dans contexte Orange", -1, 0, nil},
	31:  {"group", -1, 0, nil},
	32:  {"Non utilises dans contexte Orange", -1, 0, nil},
	33:  {"Non utilises dans contexte Orange", -1, 0, nil},
	34:  {"Non utilises dans contexte Orange", -1, 0, nil},
	35:  {"originalCalledNumber", -1, 0, nil},
	36:  {"originalCalledPresentationIndicator", -1, 0, nil},
	37:  {"originalCalledReason", -1, 0, nil},
	38:  {"redirectingNumber", -1, 0, nil},
	39:  {"redirectingPresentationIndicator", -1, 0, nil},
	40:  {"redirectingReason", -1, 0, nil},
	41:  {"chargeIndicator", -1, 0, nil},
	42:  {"typeOfNetwork", -1, 0, nil},
	43:  {"voicePortalCalling", -1, 0, nil},
	44:  {"localCallId", -1, 0, nil},
	45:  {"remoteCallId", -1, 0, nil},
	46:  {"Non utilises dans contexte Orange", -1, 0, nil},
	47:  {"Non utilises dans contexte Orange", -1, 0, nil},
	48:  {"Non utilises dans contexte Orange", -1, 0, nil},
	49:  {"Non utilises dans contexte Orange", -1, 0, nil},
	50:  {"Non utilises dans contexte Orange", -1, 0, nil},
	51:  {"Non utilises dans contexte Orange", -1, 0, nil},
	52:  {"Non utilises dans contexte Orange", -1, 0, nil},
	53:  {"Non utilises dans contexte Orange", -1, 0, nil},
	54:  {"Non utilises dans contexte Orange", -1, 0, nil},
	55:  {"Non utilises dans contexte Orange", -1, 0, nil},
	56:  {"Non utilises dans contexte Orange", -1, 0, nil},
	57:  {"Non utilises dans contexte Orange", -1, 0, nil},
	58:  {"key", -1, 0, nil},
	59:  {"creator", -1, 0, nil},
	60:  {"originatorNetwork", -1, 0, nil},
	61:  {"terminatorNetwork", -1, 0, nil},
	62:  {"Non utilises dans contexte Orange", -1, 0, nil},
	63:  {"Non utilises dans contexte Orange", -1, 0, nil},
	64:  {"Non utilises dans contexte Orange", -1, 0, nil},
	65:  {"Non utilises dans contexte Orange", -1, 0, nil},
	66:  {"Non utilises dans contexte Orange", -1, 0, nil},
	67:  {"Non utilises dans contexte Orange", -1, 0, nil},
	68:  {"Non utilises dans contexte Orange", -1, 0, nil},
	69:  {"Non utilises dans contexte Orange", -1, 0, nil},
	70:  {"Non utilises dans contexte Orange", -1, 0, nil},
	71:  {"Non utilises dans contexte Orange", -1, 0, nil},
	72:  {"Non utilises dans contexte Orange", -1, 0, nil},
	73:  {"Non utilises dans contexte Orange", -1, 0, nil},
	74:  {"Non utilises dans contexte Orange", -1, 0, nil},
	75:  {"Non utilises dans contexte Orange", -1, 0, nil},
	76:  {"Non utilises dans contexte Orange", -1, 0, nil},
	77:  {"Non utilises dans contexte Orange", -1, 0, nil},
	78:  {"Non utilises dans contexte Orange", -1, 0, nil},
	79:  {"Non utilises dans contexte Orange", -1, 0, nil},
	80:  {"cfaActivation.invocationTime", -1, 0, nil},
	81:  {"cfaActivation.facResult", -1, 0, nil},
	82:  {"cfaDeactivation.invocationTime", -1, 0, nil},
	83:  {"cfaDeactivation.facResult", -1, 0, nil},
	84:  {"cfbActivation.invocationTime", -1, 0, nil},
	85:  {"cfbActivation.facResult", -1, 0, nil},
	86:  {"cfbDeactivation.invocationTime", -1, 0, nil},
	87:  {"cfbDeactivation.facResult", -1, 0, nil},
	88:  {"cfnaActivation.invocationTime", -1, 0, nil},
	89:  {"cfnaActivation.facResult", -1, 0, nil},
	90:  {"cfnaDeactivation.invocationTime", -1, 0, nil},
	91:  {"cfnaDeactivation.facResult", -1, 0, nil},
	92:  {"clidDeliveryPerCall.invocationTime", -1, 0, nil},
	93:  {"clidDeliveryPerCall.facResult", -1, 0, nil},
	94:  {"clidBlockingPerCall.invocationTime", -1, 0, nil},
	95:  {"clidBlockingPerCall.facResult", -1, 0, nil},
	96:  {"Non utilises dans contexte Orange", -1, 0, nil},
	97:  {"Non utilises dans contexte Orange", -1, 0, nil},
	98:  {"Non utilises dans contexte Orange", -1, 0, nil},
	99:  {"Non utilises dans contexte Orange", -1, 0, nil},
	100: {"Non utilises dans contexte Orange", -1, 0, nil},
	101: {"Non utilises dans contexte Orange", -1, 0, nil},
	102: {"Non utilises dans contexte Orange", -1, 0, nil},
	103: {"Non utilises dans contexte Orange", -1, 0, nil},
	104: {"Non utilises dans contexte Orange", -1, 0, nil},
	105: {"Non utilises dans contexte Orange", -1, 0, nil},
	106: {"Non utilises dans contexte Orange", -1, 0, nil},
	107: {"Non utilises dans contexte Orange", -1, 0, nil},
	108: {"Non utilises dans contexte Orange", -1, 0, nil},
	109: {"Non utilises dans contexte Orange", -1, 0, nil},
	110: {"lastNumberRedial.invocationTime", -1, 0, nil},
	111: {"lastNumberRedial.facResult", -1, 0, nil},
	112: {"returnCall.invocationTime", -1, 0, nil},
	113: {"returnCall.facResult", -1, 0, nil},
	114: {"Non utilises dans contexte Orange", -1, 0, nil},
	115: {"Non utilises dans contexte Orange", -1, 0, nil},
	116: {"Non utilises dans contexte Orange", -1, 0, nil},
	117: {"Non utilises dans contexte Orange", -1, 0, nil},
	118: {"Non utilises dans contexte Orange", -1, 0, nil},
	119: {"Non utilises dans contexte Orange", -1, 0, nil},
	120: {"userId", -1, 0, nil},
	121: {"otherPartyName", -1, 0, nil},
	122: {"otherPartyNamePresentationIndicator", -1, 0, nil},
	123: {"Non utilises dans contexte Orange", -1, 0, nil},
	124: {"Non utilises dans contexte Orange", -1, 0, nil},
	125: {"Non utilises dans contexte Orange", -1, 0, nil},
	126: {"Non utilises dans contexte Orange", -1, 0, nil},
	127: {"Non utilises dans contexte Orange", -1, 0, nil},
	128: {"Non utilises dans contexte Orange", -1, 0, nil},
	129: {"Non utilises dans contexte Orange", -1, 0, nil},
	130: {"Non utilises dans contexte Orange", -1, 0, nil},
	131: {"Non utilises dans contexte Orange", -1, 0, nil},
	132: {"Non utilises dans contexte Orange", -1, 0, nil},
	133: {"Non utilises dans contexte Orange", -1, 0, nil},
	134: {"Non utilises dans contexte Orange", -1, 0, nil},
	135: {"Non utilises dans contexte Orange", -1, 0, nil},
	136: {"Non utilises dans contexte Orange", -1, 0, nil},
	137: {"Non utilises dans contexte Orange", -1, 0, nil},
	138: {"Non utilises dans contexte Orange", -1, 0, nil},
	139: {"Non utilises dans contexte Orange", -1, 0, nil},
	140: {"clidPermitted", -1, 0, nil},
	141: {"Non utilises dans contexte Orange", -1, 0, nil},
	142: {"Non utilises dans contexte Orange", -1, 0, nil},
	143: {"accessNetworkInfo", -1, 0, nil},
	144: {"non utilise", -1, 0, nil},
	145: {"charge number", -1, 0, nil},
	146: {"relatedCallId", -1, 0, nil},
	147: {"relatedCallIdReason", -1, 0, nil},
	148: {"transfer.invocationTime", -1, 0, nil},
	149: {"transfer.result", -1, 0, nil},
	150: {"transfer.relatedCallId", -1, 0, nil},
	151: {"transfer.type", -1, 0, nil},
	152: {"Non utilises dans contexte Orange", -1, 0, nil},
	153: {"Non utilises dans contexte Orange", -1, 0, nil},
	154: {"Non utilises dans contexte Orange", -1, 0, nil},
	155: {"Non utilises dans contexte Orange", -1, 0, nil},
	156: {"codecUsage", -1, 0, nil},
	157: {"vmBusyActivation.invocationTime", -1, 0, nil},
	158: {"vmBusyActivation.facResult", -1, 0, nil},
	159: {"vmBusyDeactivation.invocationTime", -1, 0, nil},
	160: {"vmBusyDeactivation.facResult", -1, 0, nil},
	161: {"vmNoAnswerActivation.invocationTime", -1, 0, nil},
	162: {"vmNoAnswerActivation.facResult", -1, 0, nil},
	163: {"vmNoAnswerDeactivation.invocationTime", -1, 0, nil},
	164: {"vmNoAnswerDeactivation.facResult", -1, 0, nil},
	165: {"vmAlwaysActivation.invocationTime", -1, 0, nil},
	166: {"vmAlwaysActivation.facResult", -1, 0, nil},
	167: {"vmAlwaysDeactivation.invocationTime", -1, 0, nil},
	168: {"vmAlwaysDeactivation.facResult", -1, 0, nil},
	169: {"noAnswerTimerSet.invocationTime	", -1, 0, nil},
	170: {"noAnswerTimerSet.facResult", -1, 0, nil},
	171: {"clidBlockingActivation.invocationTime", -1, 0, nil},
	172: {"clidBlockingActivation.facResult", -1, 0, nil},
	173: {"clidBlockingDeactivation.invocationTime", -1, 0, nil},
	174: {"clidBlockingDeactivation.facResult", -1, 0, nil},
	175: {"callWaitingActivation.invocationTime", -1, 0, nil},
	176: {"callWaitingActivation.facResult", -1, 0, nil},
	177: {"callWaitingDeactivation.invocationTime", -1, 0, nil},
	178: {"callWaitingDeactivation.facResult", -1, 0, nil},
	179: {"Non utilises dans contexte Orange", -1, 0, nil},
	180: {"Non utilises dans contexte Orange", -1, 0, nil},
	181: {"Non utilises dans contexte Orange", -1, 0, nil},
	182: {"Non utilises dans contexte Orange", -1, 0, nil},
	183: {"Non utilises dans contexte Orange", -1, 0, nil},
	184: {"Non utilises dans contexte Orange", -1, 0, nil},
	185: {"Non utilises dans contexte Orange", -1, 0, nil},
	186: {"Non utilises dans contexte Orange", -1, 0, nil},
	187: {"q850Cause", -1, 0, nil},
	188: {"Non utilises dans contexte Orange", -1, 0, nil},
	189: {"Non utilises dans contexte Orange", -1, 0, nil},
	190: {"Non utilises dans contexte Orange", -1, 0, nil},
	191: {"Non utilises dans contexte Orange", -1, 0, nil},
	192: {"Non utilises dans contexte Orange", -1, 0, nil},
	193: {"Non utilises dans contexte Orange", -1, 0, nil},
	194: {"Non utilises dans contexte Orange", -1, 0, nil},
	195: {"Non utilises dans contexte Orange", -1, 0, nil},
	196: {"Non utilises dans contexte Orange", -1, 0, nil},
	197: {"routingNumber", -1, 0, nil},
	198: {"Non utilises dans contexte Orange", -1, 0, nil},
	199: {"Non utilises dans contexte Orange", -1, 0, nil},
	200: {"Non utilises dans contexte Orange", -1, 0, nil},
	201: {"Non utilises dans contexte Orange", -1, 0, nil},
	202: {"Non utilises dans contexte Orange", -1, 0, nil},
	203: {"Non utilises dans contexte Orange", -1, 0, nil},
	204: {"Non utilises dans contexte Orange", -1, 0, nil},
	205: {"Non utilises dans contexte Orange", -1, 0, nil},
	206: {"Non utilises dans contexte Orange", -1, 0, nil},
	207: {"calledAssertedIdentity", -1, 0, nil},
	208: {"calledAssertedPresentationIndicator", -1, 0, nil},
	209: {"sdp", -1, 0, nil},
	210: {"mediaInitiatorFlag", -1, 0, nil},
	211: {"sdpOfferTimestamp", -1, 0, nil},
	212: {"sdpAnswerTimestamp", -1, 0, nil},
	213: {"earlyMediaSdp", -1, 0, nil},
	214: {"earlyMediaInitiatorFlag", -1, 0, nil},
	215: {"bodyContentType", -1, 0, nil},
	216: {"bodyContentLength", -1, 0, nil},
	217: {"bodyContentDisposition", -1, 0, nil},
	218: {"bodyOriginato", -1, 0, nil},
	219: {"sipErrorCode", -1, 0, nil},
	220: {"otherInfoInPCV", -1, 0, nil},
	221: {"receivedCallingNumber", -1, 0, nil},
	222: {"Non utilises dans contexte Orange", -1, 0, nil},
	223: {"Non utilises dans contexte Orange", -1, 0, nil},
	224: {"Non utilises dans contexte Orange", -1, 0, nil},
	225: {"Non utilises dans contexte Orange", -1, 0, nil},
	226: {"Non utilises dans contexte Orange", -1, 0, nil},
	227: {"Non utilises dans contexte Orange", -1, 0, nil},
	228: {"Non utilises dans contexte Orange", -1, 0, nil},
	229: {"Non utilises dans contexte Orange", -1, 0, nil},
	230: {"asCallType", -1, 0, nil},
	231: {"Non utilises dans contexte Orange", -1, 0, nil},
	232: {"Non utilises dans contexte Orange", -1, 0, nil},
	233: {"Non utilises dans contexte Orange", -1, 0, nil},
	234: {"Non utilises dans contexte Orange", -1, 0, nil},
	235: {"Non utilises dans contexte Orange", -1, 0, nil},
	236: {"Non utilises dans contexte Orange", -1, 0, nil},
	237: {"Non utilises dans contexte Orange", -1, 0, nil},
	238: {"Non utilises dans contexte Orange", -1, 0, nil},
	239: {"Non utilises dans contexte Orange", -1, 0, nil},
	240: {"Non utilises dans contexte Orange", -1, 0, nil},
	241: {"Non utilises dans contexte Orange", -1, 0, nil},
	242: {"Non utilises dans contexte Orange", -1, 0, nil},
	243: {"returnCallNumberDeletion.invocationTime", -1, 0, nil},
	244: {"returnCallNumDel.facResult", -1, 0, nil},
	245: {"Non utilises dans contexte Orange", -1, 0, nil},
	246: {"Non utilises dans contexte Orange", -1, 0, nil},
	247: {"Non utilises dans contexte Orange", -1, 0, nil},
	248: {"Non utilises dans contexte Orange", -1, 0, nil},
	249: {"Non utilises dans contexte Orange", -1, 0, nil},
	250: {"Non utilises dans contexte Orange", -1, 0, nil},
	251: {"Non utilises dans contexte Orange", -1, 0, nil},
	252: {"Non utilises dans contexte Orange", -1, 0, nil},
	253: {"Non utilises dans contexte Orange", -1, 0, nil},
	254: {"interceptUser.routingNumber", -1, 0, nil},
	255: {"interceptGroup.routingNumber", -1, 0, nil},
	256: {"Non utilises dans contexte Orange", -1, 0, nil},
	257: {"Non utilises dans contexte Orange", -1, 0, nil},
	258: {"Non utilises dans contexte Orange", -1, 0, nil},
	259: {"Non utilises dans contexte Orange", -1, 0, nil},
	260: {"Non utilises dans contexte Orange", -1, 0, nil},
	261: {"Non utilises dans contexte Orange", -1, 0, nil},
	262: {"Non utilises dans contexte Orange", -1, 0, nil},
	263: {"Non utilises dans contexte Orange", -1, 0, nil},
	264: {"Non utilises dans contexte Orange", -1, 0, nil},
	265: {"Non utilises dans contexte Orange", -1, 0, nil},
	266: {"Non utilises dans contexte Orange", -1, 0, nil},
	267: {"Non utilises dans contexte Orange", -1, 0, nil},
	268: {"Non utilises dans contexte Orange", -1, 0, nil},
	269: {"Non utilises dans contexte Orange", -1, 0, nil},
	270: {"Non utilises dans contexte Orange", -1, 0, nil},
	271: {"namePermitted", -1, 0, nil},
	272: {"Non utilises dans contexte Orange", -1, 0, nil},
	273: {"Non utilises dans contexte Orange", -1, 0, nil},
	274: {"Non utilises dans contexte Orange", -1, 0, nil},
	275: {"Non utilises dans contexte Orange", -1, 0, nil},
	276: {"Non utilises dans contexte Orange", -1, 0, nil},
	277: {"Non utilises dans contexte Orange", -1, 0, nil},
	278: {"Non utilises dans contexte Orange", -1, 0, nil},
	279: {"Non utilises dans contexte Orange", -1, 0, nil},
	280: {"Non utilises dans contexte Orange", -1, 0, nil},
	281: {"Non utilises dans contexte Orange", -1, 0, nil},
	282: {"Non utilises dans contexte Orange", -1, 0, nil},
	283: {"Non utilises dans contexte Orange", -1, 0, nil},
	284: {"Non utilises dans contexte Orange", -1, 0, nil},
	285: {"Non utilises dans contexte Orange", -1, 0, nil},
	286: {"Non utilises dans contexte Orange", -1, 0, nil},
	287: {"Non utilises dans contexte Orange", -1, 0, nil},
	288: {"Non utilises dans contexte Orange", -1, 0, nil},
	289: {"Non utilises dans contexte Orange", -1, 0, nil},
	290: {"Non utilises dans contexte Orange", -1, 0, nil},
	291: {"Non utilises dans contexte Orange", -1, 0, nil},
	292: {"Non utilises dans contexte Orange", -1, 0, nil},
	293: {"Non utilises dans contexte Orange", -1, 0, nil},
	294: {"Non utilises dans contexte Orange", -1, 0, nil},
	295: {"Non utilises dans contexte Orange", -1, 0, nil},
	296: {"dialableCallingNumber", -1, 0, nil},
	297: {"Non utilises dans contexte Orange", -1, 0, nil},
	298: {"Non utilises dans contexte Orange", -1, 0, nil},
	299: {"Non utilises dans contexte Orange", -1, 0, nil},
	300: {"Non utilises dans contexte Orange", -1, 0, nil},
	301: {"Non utilises dans contexte Orange", -1, 0, nil},
	302: {"Non utilises dans contexte Orange", -1, 0, nil},
	303: {"Non utilises dans contexte Orange", -1, 0, nil},
	304: {"Non utilises dans contexte Orange", -1, 0, nil},
	305: {"Non utilises dans contexte Orange", -1, 0, nil},
	306: {"Non utilises dans contexte Orange", -1, 0, nil},
	307: {"Non utilises dans contexte Orange", -1, 0, nil},
	308: {"Non utilises dans contexte Orange", -1, 0, nil},
	309: {"Non utilises dans contexte Orange", -1, 0, nil},
	310: {"Non utilises dans contexte Orange", -1, 0, nil},
	311: {"location", -1, 0, nil},
	312: {"locationType", -1, 0, nil},
	313: {"locationUsage", -1, 0, nil},
	314: {"Non utilises", -1, 0, nil},
	315: {"Non utilises", -1, 0, nil},
	316: {"Non utilises", -1, 0, nil},
	317: {"Non utilises", -1, 0, nil},
	318: {"Non utilises", -1, 0, nil},
	319: {"callingPresentationNumber", -1, 0, nil},
	320: {"Non utilises", -1, 0, nil},
	321: {"callingAssertedNumber", -1, 0, nil},
	322: {"Non utilises", -1, 0, nil},
	323: {"Non utilises", -1, 0, nil},
	324: {"Non utilises", -1, 0, nil},
	325: {"Non utilises", -1, 0, nil},
	326: {"Non utilises", -1, 0, nil},
	327: {"Non utilises", -1, 0, nil},
	328: {"Non utilises", -1, 0, nil},
	329: {"Non utilises", -1, 0, nil},
	330: {"Non utilises", -1, 0, nil},
	331: {"Non utilises", -1, 0, nil},
	332: {"Non utilises", -1, 0, nil},
	333: {"Non utilises", -1, 0, nil},
	334: {"Non utilises", -1, 0, nil},
	335: {"Non utilises", -1, 0, nil},
	336: {"Non utilises", -1, 0, nil},
	337: {"Non utilises", -1, 0, nil},
	338: {"Non utilises", -1, 0, nil},
	339: {"Non utilises", -1, 0, nil},
	340: {"Non utilises", -1, 0, nil},
	341: {"Non utilises", -1, 0, nil},
	342: {"Non utilises", -1, 0, nil},
	343: {"Non utilises", -1, 0, nil},
	344: {"Non utilises", -1, 0, nil},
	345: {"userAgent", -1, 0, nil},
	346: {"Non utilises dans contexte Orange", -1, 0, nil},
	347: {"Non utilises dans contexte Orange", -1, 0, nil},
	348: {"Non utilises dans contexte Orange", -1, 0, nil},
	349: {"Non utilises dans contexte Orange", -1, 0, nil},
	350: {"Non utilises dans contexte Orange", -1, 0, nil},
	351: {"Non utilises dans contexte Orange", -1, 0, nil},
	352: {"Non utilises dans contexte Orange", -1, 0, nil},
	353: {"Non utilises dans contexte Orange", -1, 0, nil},
	354: {"Non utilises dans contexte Orange", -1, 0, nil},
	355: {"Non utilises dans contexte Orange", -1, 0, nil},
	356: {"Non utilises dans contexte Orange", -1, 0, nil},
	357: {"Non utilises dans contexte Orange", -1, 0, nil},
	358: {"Non utilises dans contexte Orange", -1, 0, nil},
	359: {"Non utilises dans contexte Orange", -1, 0, nil},
	360: {"Non utilises dans contexte Orange", -1, 0, nil},
	361: {"Non utilises dans contexte Orange", -1, 0, nil},
	362: {"callingPartyAddress", -1, 0, nil},
	363: {"Non utilises", -1, 0, nil},
	364: {"Non utilises", -1, 0, nil},
	365: {"Non utilises", -1, 0, nil},
	366: {"Non utilises", -1, 0, nil},
	367: {"Non utilises", -1, 0, nil},
	368: {"Non utilises", -1, 0, nil},
	369: {"Non utilises", -1, 0, nil},
	370: {"Non utilises", -1, 0, nil},
	371: {"extTrackingId", -1, 0, nil},
	372: {"Non utilises", -1, 0, nil},
	373: {"Non utilises", -1, 0, nil},
	374: {"Non utilises", -1, 0, nil},
	375: {"Non utilises", -1, 0, nil},
	376: {"Non utilises", -1, 0, nil},
	377: {"Non utilises", -1, 0, nil},
	378: {"Non utilises", -1, 0, nil},
	379: {"Non utilises", -1, 0, nil},
	380: {"Non utilises", -1, 0, nil},
	381: {"Non utilises", -1, 0, nil},
	382: {"Non utilises", -1, 0, nil},
	383: {"Non utilises", -1, 0, nil},
	384: {"Non utilises", -1, 0, nil},
	385: {"Non utilises", -1, 0, nil},
	386: {"Non utilises", -1, 0, nil},
	387: {"Non utilises", -1, 0, nil},
	388: {"Non utilises", -1, 0, nil},
	389: {"Non utilises", -1, 0, nil},
	390: {"Non utilises", -1, 0, nil},
	391: {"Non utilises", -1, 0, nil},
	392: {"Non utilises", -1, 0, nil},
	393: {"Non utilises", -1, 0, nil},
	394: {"Non utilises", -1, 0, nil},
	395: {"Non utilises", -1, 0, nil},
	396: {"Non utilises", -1, 0, nil},
	397: {"Non utilises", -1, 0, nil},
	398: {"Non utilises", -1, 0, nil},
	399: {"Non utilises", -1, 0, nil},
	400: {"Non utilises", -1, 0, nil},
	401: {"Non utilises", -1, 0, nil},
	402: {"Non utilises", -1, 0, nil},
	403: {"Non utilises", -1, 0, nil},
	404: {"collaborate.invocationTime", -1, 0, nil},
	405: {"collaborate.roomID", -1, 0, nil},
	406: {"collaborate.role", -1, 0, nil},
	407: {"collaborate.bridge", -1, 0, nil},
	408: {"collaborate.owner", -1, 0, nil},
	409: {"collaborate.ownerDN", -1, 0, nil},
	410: {"collaborate.roomName", -1, 0, nil},
	411: {"collaborate.roomType", -1, 0, nil},
	412: {"non utilises", -1, 0, nil},
	413: {"non utilises", -1, 0, nil},
	414: {"non utilises", -1, 0, nil},
	415: {"non utilises", -1, 0, nil},
	416: {"non utilises", -1, 0, nil},
	417: {"non utilises", -1, 0, nil},
	418: {"non utilises", -1, 0, nil},
	419: {"non utilises", -1, 0, nil},
	420: {"non utilises", -1, 0, nil},
	421: {"non utilises", -1, 0, nil},
	422: {"non utilises", -1, 0, nil},
	423: {"non utilises", -1, 0, nil},
	424: {"non utilises", -1, 0, nil},
	425: {"non utilises", -1, 0, nil},
	426: {"non utilises", -1, 0, nil},
	427: {"non utilises", -1, 0, nil},
	428: {"non utilises", -1, 0, nil},
	429: {"non utilises", -1, 0, nil},
	430: {"non utilises", -1, 0, nil},
	431: {"non utilises", -1, 0, nil},
	432: {"non utilises", -1, 0, nil},
	433: {"non utilises", -1, 0, nil},
}

var failover = map[int]defStructs.Champ{
	1:  {"recordId", -1, 0, nil},
	2:  {"serviceProviderId", -1, 0, nil},
	3:  {"type", -1, 0, nil},
	4:  {"userNumber", -1, 0, nil},
	5:  {"groupNumber", -1, 0, nil},
	6:  {"direction", -1, 0, nil},
	7:  {"callingNumber", -1, 0, nil},
	8:  {"callingPresentationIndicator", -1, 0, nil},
	9:  {"calledNumber", -1, 0, nil},
	10: {"startTime", -1, 0, nil},
	11: {"userTimeZone", -1, 0, nil},
	12: {"answerIndicator", -1, 0, nil},
	13: {"answerTime", -1, 0, nil},
	14: {"releaseTime", -1, 11, nil},
	15: {"terminationCause", -1, 0, nil},
	16: {"networkType", -1, 0, nil},
	17: {"Non utilise dans contexte Orange", -1, 0, nil},
	18: {"dialedDigits", -1, 0, nil},
	19: {"Non utilises dans contexte Orange", -1, 0, nil},
	20: {"Non utilises dans contexte Orange", -1, 0, nil},
	21: {"Non utilises dans contexte Orange", -1, 0, nil},
	22: {"Non utilises dans contexte Orange", -1, 0, nil},
	23: {"releasingParty", -1, 0, nil},
	24: {"failoverCorrelationId", -1, 0, nil},
	25: {"chargeIndicator", -1, 0, nil},
	26: {"typeOfNetwork", -1, 0, nil},
	27: {"userId", -1, 0, nil},
	28: {"otherPartyName", -1, 0, nil},
	29: {"otherPartyNamePresentationIndicator", -1, 0, nil},
	30: {"localCallId", -1, 0, nil},
	31: {"remoteCallId", -1, 0, nil},
	32: {"clidPermitted", -1, 0, nil},
	33: {"q850Cause", -1, 0, nil},
	34: {"Non utilises dans contexte Orange", -1, 0, nil},
	35: {"Non utilises dans contexte Orange", -1, 0, nil},
	36: {"Non utilises dans contexte Orange", -1, 0, nil},
	37: {"Non utilises dans contexte Orange", -1, 0, nil},
	38: {"receivedCallingNumber", -1, 0, nil},
	39: {"asCallType", -1, 0, nil},
	40: {"namePermitted", -1, 0, nil},
	41: {"dialableCallingNumber", -1, 0, nil},
	42: {"Non utilises dans contexte Orange", -1, 0, nil},
	43: {"Non utilises dans contexte Orange", -1, 0, nil},
	44: {"Non utilises dans contexte Orange", -1, 0, nil},
	45: {"Non utilises dans contexte Orange", -1, 0, nil},
	46: {"Non utilises dans contexte Orange", -1, 0, nil},
	47: {"Non utilises dans contexte Orange", -1, 0, nil},
	48: {"Non utilises dans contexte Orange", -1, 0, nil},
	49: {"Non utilises dans contexte Orange", -1, 0, nil},
}
